.TH RATIUM 1 ratium\-VERSION
.SH NAME
ratium \- A Dumb Little NCurses ASCII Game
.SH SYNOPSIS
.B ratium [-hv] [--help] [--version]
.SH DESCRIPTION
ratium is a dumb little game where you are a '@' and have survive in an ASCII 
world by defending yourself from various enemies, such as the super rat.
Collect items such as spam, swords, and haggises to survive.
.SH COMMANDS
To quit game press 'q' or ESC, you can also press ctrl-z to suspend the game,
exiting to your shell where you can enter 'fg' to bring it back up again.
.IP
.SS MOVEMENT
.IP
.BR h
Move player left.
.IP
.BR j
Move player down.
.IP
.BR k
Move player up.
.IP
.BR l
Move player right.
.IP
.SS PLAYER ACTIONS
.IP
.BR g
Get item under player.
.IP
.BR o
Open/close door.
.IP
.BR i
Open inventory menu.
.IP
.SS INVENTORY
.IP
.BR i
Exit from inventory menu.
.IP
.BR g
Use item, depending on item type you can eat it or equip it in hand.
.IP
.BR d
Drop item onto map.
.SH ENTITIES
.TP
.BR Rat\ (r)
A hostile creature which deals 1 damage and has 2 heath. Drops rat meat when it
dies.
.TP
.BR Super\ Rat\ (R)
A hostile creature which deals 2 damage and has 4 heath. Drops rat meat when it
dies.
.IP
.TP
.BR Gnu\ (G)
A peaceful animal with 6 heath. Drops gnu meat when it dies
